- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  width: wide
  center-vertically: false
  head-widgets:
    - type: group
      title: System & Services Status
      widgets:
        - type: server-stats
          title: System Status
          cache: 1m
          servers:
            - type: local
              name: Services
        - type: monitor
          cache: 1m
          title: My Services
          show-response-time: true
          sites:
            - title: My Website
              url: https://irfansp.dev
            - title: My Online Resume
              url: https://resume.irfansp.dev
            - title: My AI assistant
              url: https://ai.irfansp.dev
            - title: My n8n
              url: https://automate.irfansp.dev
            - title: My Second Brain
              url: https://brain.irfansp.dev
            - title: My TILs
              url: https://til.irfansp.dev
            - title: My Bookmarks
              url: https://linkwarden.irfansp.dev
            - title: My SearXng
              url: https://searxng.irfansp.dev
            - title: My Dokploy
              url: https://dokploy.irfansp.dev

  columns:
    - size: small
      widgets:
        - type: search
          search-engine: https://searxng.irfansp.dev/search?q={QUERY}
          title: Search

        - type: to-do
          title: My Tasks

        - type: calendar
          first-day-of-week: monday
          title: My Calendar

        - type: weather
          location: Jakarta, Indonesia
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
          cache: 1h

    - size: full
      widgets:
        - type: group
          title: News & Updates
          widgets:
            - type: rss
              title: Tech & Engineering Blogs
              limit: 10
              collapse-after: 3
              cache: 6h
              style: cards
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st
                - url: https://bytebytego.substack.com/feed
                  title: ByteByteGo
                - url: https://pragmaticengineer.substack.com/feed
                  title: Pragmatic Engineer
                - url: https://algomaster.substack.com/feed
                  title: AlgoMaster
                - url: https://simonwillison.net/atom/everything/
                  title: Simon Willison
                - url: https://dekontaminasi.substack.com/feed
                  title: Dekontaminasi
                - url: https://feeds.dzone.com/home
                  title: DZone
                - url: https://hellointerview.substack.com/feed
                  title: Hello Interview
                - url: https://highgrowthengineer.substack.com/feed
                  title: High Growth Engineer
                - url: https://refactoring.fm/feed
                  title: Refactoring.fm
                - url: https://www.architecture-weekly.com/feed
                  title: Architecture Weekly
                - url: https://hnrss.org/best
                  title: Hacker News Best
                - url: https://martinfowler.com/bliki/bliki.atom
                  title: Martin Fowler
                - url: https://devops.com/feed/
                  title: DevOps.com
                - url: https://aws.amazon.com/blogs/aws/feed/
                  title: AWS Blog
                - url: https://thenewstack.io/feed
                  title: The New Stack
            - type: hacker-news
              title: Hacker News
              limit: 10
              cache: 30m

        - type: videos
          title: Tech Videos
          cache: 2h
          limit: 12
          channels:
            - UC0m81bQuthaQZmFbXEY9QSw # The AICode king
            - UC14ZKB9XsDZbnHVmr4AmUpQ # PZN
            - UC_ML5xP23TOWKUcc-oAE_Eg # Hussein Nasser
            - UClNlh5F6zcOD_grYOhbdezQ # Three dots lab
            - UCPbwhExawYrn9xxI21TFfyw # The Pragmatic Engineer
            - UC3ds0MBQZ7dBoeIG8YeddOg # Gogo
            - UCdngmbVKX1Tgre699-XLlUA # Tech world with Nana
            - UCE4PyAWiZ5gdPVFxDe4lLPQ # AI Oriented dev

        - type: group
          title: Reddit Communities
          widgets:
            - type: reddit
              title: r/technology
              subreddit: technology
              show-thumbnails: true
              limit: 8
              cache: 1h
            - type: reddit
              title: r/selfhosted
              subreddit: selfhosted
              show-thumbnails: true
              limit: 8
              cache: 1h

    - size: small
      widgets:
        - type: group
          title: Financial Markets
          widgets:
            - type: markets
              title: Global Markets & Crypto
              cache: 5m
              sort-by: "change"
              markets:
                - symbol: USDIDR=X
                  name: USD/IDR
                - symbol: BTC-USD
                  name: Bitcoin
                - symbol: ^JKSE
                  name: IDX Composite
                - symbol: SPY
                  name: S&P 500

            - type: markets
              title: Indonesian Banks
              cache: 5m
              sort-by: "change"
              markets:
                - symbol: bbca.jk
                  name: Bank Central Asia
                - symbol: bbri.jk
                  name: Bank Rakyat Indonesia
                - symbol: bmri.jk
                  name: Bank Mandiri
                - symbol: bnga.jk
                  name: Bank CIMB Niaga
                - symbol: nisp.jk
                  name: Bank NISP

            - type: markets
              title: Other Stocks
              cache: 5m
              sort-by: "change"
              markets:
                - symbol: aadi.jk
                  name: Astra Digital Indonesia
                - symbol: asii.jk
                  name: Astra International
                - symbol: abmm.jk
                  name: PT ABM Investama Tbk
                - symbol: admr.jk
                  name: Adaro Minerals Indonesia Tbk
                - symbol: adro.jk
                  name: Adaro Resources Tbk
                - symbol: ptba.jk
                  name: Bukit Asam Tbk
                - symbol: brms.jk
                  name: Bumi Resources Minerals Tbk.
                - symbol: midi.jk
                  name: Midi Utama Indonesia Tbk.
                - symbol: goto.jk
                  name: Goto Indonesia Tbk.